Repository danirod/cartero, pull requests merged in 2024-07, with the labels that each got.

#37 Compilation script for macOS
  .github/workflows/nightly.yaml
  MACOS.md
  build-aux/macos-build.sh
  build-aux/macos-installer.sh
  po/LINGUAS
  src/main.rs
Labels: macOS

#40 Add dynamic color for status code
  src/widgets/response_panel.rs
Labels: Pending backport

#41 Add Romanian translation for Cartero
  build-aux/macos-build.sh
  po/LINGUAS
  po/ro.po
Labels: Pending backport

#44 Nix packaging
  README.md
  default.nix
Labels: Pending backport

#46 Include gspawn-win64-helper on Windows
  build-aux/msys-build.sh
Labels: Pending backport

#54 Ergonomic changes to the request panel
  data/ui/endpoint_pane.blp
  data/ui/response_panel.blp
  src/widgets/endpoint_pane.rs
Labels: Pending backport

#47 Flathub requirements
  .editorconfig
  NEWS.md
  README.md
  data/cartero.appdata.xml.in.in
  data/cartero.desktop.in.in
  data/meson.build
  data/screenshots/cartero-default-dark.png
  data/screenshots/cartero-default-dark@2x.png
  data/screenshots/cartero-default.png
  data/screenshots/cartero-default@2x.png
  data/screenshots/cartero-headers-dark.png
  data/screenshots/cartero-headers-dark@2x.png
  data/screenshots/cartero-headers.png
  data/screenshots/cartero-headers@2x.png
  data/screenshots/cartero-payload-dark.png
  data/screenshots/cartero-payload-dark@2x.png
  data/screenshots/cartero-payload.png
  data/screenshots/cartero-payload@2x.png
  doc/cartero-screenshot.png
  po/POTFILES.in
  po/cartero.pot
  po/en.po
  po/eo.po
  po/es.po
  po/ro.po
  src/app.rs
  src/file.rs
  src/main.rs
  src/utils/mod.rs
  src/widgets/file_dialogs.rs
  src/widgets/item_pane.rs
  src/win.rs
Labels: Bug, Pending backport

#55 add support fot catalan language
  build-aux/macos-build.sh
  po/LINGUAS
  po/ca.po
Labels: Pending backport
